version: '3'
services:

  web:
    container_name: web
    image: ycat01/hibit
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: ycat01/hibit-ngnix
    ports:
      - 80:80
    depends_on:
      - web